services:
    atsserver_service:
        container_name: atsserver
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./data:/home/atsserver/.local/share/American Truck Simulator"
            - "./log:/home/atsserver/log"
        dns:
            - 1.1.1.1
            - 1.0.0.1
        ports:
            - "27015:27015"
            - "27016:27016"
        restart: unless-stopped
